[package]
name = "andromeda-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
andromeda-lib = { path = "../andromeda-lib" }
windows = { version = "0.61.3", features = ["Win32_System_LibraryLoader", "Win32_Devices_HumanInterfaceDevice"] }
